services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: compose/Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    command: ["npm","run","dev","--","--host"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mssqldata:
